#!/bin/sh
#
# sailersensor initscript
#
### BEGIN INIT INFO
# Provides:          sailersensor
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sailersensor application init script
# Description:       This script starts and stops the sailersensor application
#
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

NAME=sailersensor
HOME=/home/pi/sailer-sensor/rpi
APP=$HOME/c++/$NAME.bin
LOCK=/var/lock/$NAME
LOG=/var/log/$NAME.log
CONFIG=$HOME/c++/$NAME.cfg

checkroot()
{
  if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
  fi
}
# Start the service sailersensor

start()
{
    log_daemon_msg "Starting" "sailersensor"
    if [ -f $LOCK ]; then 
	echo ". Sailsensor is already running.";
	return 0
    fi

    touch $LOCK
    $APP "$CONFIG" >> $LOG 2>&1 &
    status=$?
    log_end_msg $status
}

stop()
{
    log_daemon_msg "Stopping" "sailersensor"
    if [ ! -f $LOCK ]; then
	echo ". Sailsensor is not running."
	return 0
    else
	rm -f $LOCK
	PID=$(/bin/pidof "sailersensor.bin")
	kill $PID
	status=$?
	log_end_msg $status
    fi
}

status()
{
    echo -n "Sailersensor status: "
    if [ -f $LOCK ];
    then
	echo "Running"
    else
	echo "Not running"
    fi
}

restart()
{
    stop
    sleep 2
    start
}

checkroot
case "$1" in
    start) 
	start
    ;;
    stop)
	stop
    ;;
    status)
	status
    ;;
    restart)
	restart
    ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
    ;;
esac

exit 0