#!/bin/sh
#
# sailersensord initscript
#
### BEGIN INIT INFO
# Provides:          sailersensord
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sailersensodr daemon init script
# Description:       This script starts and stops the sailersensord daemon
#
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

NAME=sailersensord
HOME=/home/pi/sailer-sensor/rpi
DAEMON=$HOME/c++/$NAME
LOCK=/var/lock/$NAME
CONFIG=$HOME/c++/$NAME.cfg

checkroot()
{
  if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
  fi
}

start()
{
    log_daemon_msg "Starting" $NAME
    if [ -f $LOCK ]; then 
	echo ". $NAME is already running.";
	return 0
    fi

    touch $LOCK
    $DAEMON $CONFIG
    status=$?
    log_end_msg $status
}

stop()
{
    log_daemon_msg "Stopping" $NAME
    if [ ! -f $LOCK ]; then
	echo ". $NAME is not running."
	return 0
    else
	rm -f $LOCK
	PID=$(/bin/pidof $NAME)
	kill $PID
	status=$?
	log_end_msg $status
    fi
}

status()
{
    echo -n "$NAME status: "
    if [ -f $LOCK ];
    then
	echo "Running"
    else
	echo "Not running"
    fi
}

restart()
{
    stop
    sleep 2
    start
}

checkroot
case "$1" in
    start) 
	start
    ;;
    stop)
	stop
    ;;
    status)
	status
    ;;
    restart)
	restart
    ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
    ;;
esac

exit 0