#!/bin/bash

NAME=sailersensor
HOME=/home/pi/sailer-sensor/rpi
APP=$HOME/c++/$NAME.bin
LOCK=/var/lock/$NAME
LOG=/var/log/$NAME.log
CONFIG=$HOME/c++/$NAME.cfg

OK="\e[00;32m[Ok]\e[00m"
FAIL="\e[00;31m[Failed]\e[00m"

test -f $DAEMON || exit 0

. /lib/lsb/init-functions

# Start the service sailersensor

### main logic ###
case "$1" in
    start) 
	if [ -f $LOCK ];
	then 
	    /bin/echo -e "Sailsensor is already running $FAIL"
	else
	    /bin/echo  -n "Starting sailersensor..."
	    /bin/touch $LOCK
            $APP "$CONFIG" >> $LOG 2>&1 &
	    /bin/echo -e "$OK"
	fi
	;;
    stop)
	if [ ! -f $LOCK ]; then
	    /bin/echo -e "Sailsensor is not running $FAIL"
	else
	    /bin/echo  -n "Stopping sailersensor..."
	    /bin/rm -f $LOCK
	    PID=$(/bin/pidof "sailersensor.bin")
	    $(/bin/kill $PID)
	    /bin/echo -e "$OK"
	fi
        ;;
    status)
	if [ -f $LOCK ];
	then
	    /bin/echo "Sailsensor is running"
	else
	    /bin/echo "Sailsensor is not running"
	fi
        ;;
    restart|reload|condrestart)
        $0 stop
        $0 start
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 2
esac
exit 0